name: committer_cra
description: A committer application for business to manage CRA

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_svg: ^1.1.5
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  shared_preferences: ^2.0.15
  simple_gravatar: ^1.1.0
  syncfusion_flutter_calendar: ^20.3.57
  date_time: ^0.8.0
  flutter_local_notifications: ^13.0.0
  badges: ^2.0.3
  json_annotation: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  date_utils: ^0.2.0
  intl: ^0.17.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
  fonts:
    - family: lambda
      fonts:
        - asset: assets/fonts/Lambda-Italic.ttf
        - asset: assets/fonts/Lambda-Regular.ttf
          weight: 700

flutter_icons:
  image_path: "assets/logos/icon.png"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true